### ISSUE TITLE
Write access very slow on Ubuntu Mate 15.10

### ISSUE THREAD

**Issue by martinstut** [cryptomator/cryptomator-deb#1]
Debian download version 1.0.0
Ubuntu Mate 15.04/64-bit, Kernel 4.2.0-34-generic
Standard Caja file manager
syncing with OwnCloud (server in LAN)

I'm experiencing very slow write access. 8 images, totalling about 1 MB, are transferred at less than 700 Bytes/second.
CPU load is neglible.

The overhead seems to be per file, not per kB.
There seems to be a delay of exactly 3 minutes per file, which seems like a timeout.

Read access is fine.

**Comment by martinstut** [comment]
Addendum:
mounting separately via fstab helps a bit. If the option use_locks is set to 0, which could be acceptable in a single user environment, the delay is reduced to about 30 seconds.

**Comment by overheadhunter** [comment]
Both, 3 min and 30 sec is not how it should work, obviously ;) Maybe it is related to the [out of entropy problem](/cryptomator/cryptomator/issues/174)? We need new random numbers for each file.

**Comment by martinstut** [comment]
Release 1.0.3 solved the issue. Cryptomator is working great on Ubuntu Mate 15.10, sharing with Windows 7 and Windows 10 via OwnCloud 8.2.
